import Head from 'next/head'
import Header from './Header'
import Aside from './Aside'
import Footer from './Footer'


export default function Layout({ children }) {
    return (
      <div>
         <Head>
         
          <meta name="description" content="Generated by create next app" />
        
        </Head>

        <Header />

        <div className='site-center'>
          <main>{children}</main>

          <Aside />
        </div>

        <Footer />
      </div>
    )
  }