import Head from 'next/head'
import Header from './Header'
import Aside from './Aside'
import Footer from './Footer'
import styles from '../styles/Layout.module.scss'

export default function Layout({ children }) {
    return (
      <div>
        <Head>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <Header />

        <div className={styles.sitecenter}>

          <main  className={styles.mainsite}>{children}</main>

          <Aside />

        </div>

        <Footer />

      </div>
    )
  }